/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.ucsb.cs.mdcc.messaging;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Accept implements org.apache.thrift.TBase<Accept, Accept._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Accept");

  private static final org.apache.thrift.protocol.TField TRANSACTION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("transactionId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField BALLOT_FIELD_DESC = new org.apache.thrift.protocol.TField("ballot", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("key", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField OLD_VERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("oldVersion", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField NEW_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("newValue", org.apache.thrift.protocol.TType.STRING, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AcceptStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AcceptTupleSchemeFactory());
  }

  public String transactionId; // required
  public BallotNumber ballot; // required
  public String key; // required
  public long oldVersion; // required
  public ByteBuffer newValue; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TRANSACTION_ID((short)1, "transactionId"),
    BALLOT((short)2, "ballot"),
    KEY((short)3, "key"),
    OLD_VERSION((short)4, "oldVersion"),
    NEW_VALUE((short)5, "newValue");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TRANSACTION_ID
          return TRANSACTION_ID;
        case 2: // BALLOT
          return BALLOT;
        case 3: // KEY
          return KEY;
        case 4: // OLD_VERSION
          return OLD_VERSION;
        case 5: // NEW_VALUE
          return NEW_VALUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __OLDVERSION_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TRANSACTION_ID, new org.apache.thrift.meta_data.FieldMetaData("transactionId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BALLOT, new org.apache.thrift.meta_data.FieldMetaData("ballot", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BallotNumber.class)));
    tmpMap.put(_Fields.KEY, new org.apache.thrift.meta_data.FieldMetaData("key", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OLD_VERSION, new org.apache.thrift.meta_data.FieldMetaData("oldVersion", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.NEW_VALUE, new org.apache.thrift.meta_data.FieldMetaData("newValue", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Accept.class, metaDataMap);
  }

  public Accept() {
  }

  public Accept(
    String transactionId,
    BallotNumber ballot,
    String key,
    long oldVersion,
    ByteBuffer newValue)
  {
    this();
    this.transactionId = transactionId;
    this.ballot = ballot;
    this.key = key;
    this.oldVersion = oldVersion;
    setOldVersionIsSet(true);
    this.newValue = newValue;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Accept(Accept other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetTransactionId()) {
      this.transactionId = other.transactionId;
    }
    if (other.isSetBallot()) {
      this.ballot = new BallotNumber(other.ballot);
    }
    if (other.isSetKey()) {
      this.key = other.key;
    }
    this.oldVersion = other.oldVersion;
    if (other.isSetNewValue()) {
      this.newValue = org.apache.thrift.TBaseHelper.copyBinary(other.newValue);
;
    }
  }

  public Accept deepCopy() {
    return new Accept(this);
  }

  @Override
  public void clear() {
    this.transactionId = null;
    this.ballot = null;
    this.key = null;
    setOldVersionIsSet(false);
    this.oldVersion = 0;
    this.newValue = null;
  }

  public String getTransactionId() {
    return this.transactionId;
  }

  public Accept setTransactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  public void unsetTransactionId() {
    this.transactionId = null;
  }

  /** Returns true if field transactionId is set (has been assigned a value) and false otherwise */
  public boolean isSetTransactionId() {
    return this.transactionId != null;
  }

  public void setTransactionIdIsSet(boolean value) {
    if (!value) {
      this.transactionId = null;
    }
  }

  public BallotNumber getBallot() {
    return this.ballot;
  }

  public Accept setBallot(BallotNumber ballot) {
    this.ballot = ballot;
    return this;
  }

  public void unsetBallot() {
    this.ballot = null;
  }

  /** Returns true if field ballot is set (has been assigned a value) and false otherwise */
  public boolean isSetBallot() {
    return this.ballot != null;
  }

  public void setBallotIsSet(boolean value) {
    if (!value) {
      this.ballot = null;
    }
  }

  public String getKey() {
    return this.key;
  }

  public Accept setKey(String key) {
    this.key = key;
    return this;
  }

  public void unsetKey() {
    this.key = null;
  }

  /** Returns true if field key is set (has been assigned a value) and false otherwise */
  public boolean isSetKey() {
    return this.key != null;
  }

  public void setKeyIsSet(boolean value) {
    if (!value) {
      this.key = null;
    }
  }

  public long getOldVersion() {
    return this.oldVersion;
  }

  public Accept setOldVersion(long oldVersion) {
    this.oldVersion = oldVersion;
    setOldVersionIsSet(true);
    return this;
  }

  public void unsetOldVersion() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __OLDVERSION_ISSET_ID);
  }

  /** Returns true if field oldVersion is set (has been assigned a value) and false otherwise */
  public boolean isSetOldVersion() {
    return EncodingUtils.testBit(__isset_bitfield, __OLDVERSION_ISSET_ID);
  }

  public void setOldVersionIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __OLDVERSION_ISSET_ID, value);
  }

  public byte[] getNewValue() {
    setNewValue(org.apache.thrift.TBaseHelper.rightSize(newValue));
    return newValue == null ? null : newValue.array();
  }

  public ByteBuffer bufferForNewValue() {
    return newValue;
  }

  public Accept setNewValue(byte[] newValue) {
    setNewValue(newValue == null ? (ByteBuffer)null : ByteBuffer.wrap(newValue));
    return this;
  }

  public Accept setNewValue(ByteBuffer newValue) {
    this.newValue = newValue;
    return this;
  }

  public void unsetNewValue() {
    this.newValue = null;
  }

  /** Returns true if field newValue is set (has been assigned a value) and false otherwise */
  public boolean isSetNewValue() {
    return this.newValue != null;
  }

  public void setNewValueIsSet(boolean value) {
    if (!value) {
      this.newValue = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TRANSACTION_ID:
      if (value == null) {
        unsetTransactionId();
      } else {
        setTransactionId((String)value);
      }
      break;

    case BALLOT:
      if (value == null) {
        unsetBallot();
      } else {
        setBallot((BallotNumber)value);
      }
      break;

    case KEY:
      if (value == null) {
        unsetKey();
      } else {
        setKey((String)value);
      }
      break;

    case OLD_VERSION:
      if (value == null) {
        unsetOldVersion();
      } else {
        setOldVersion((Long)value);
      }
      break;

    case NEW_VALUE:
      if (value == null) {
        unsetNewValue();
      } else {
        setNewValue((ByteBuffer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TRANSACTION_ID:
      return getTransactionId();

    case BALLOT:
      return getBallot();

    case KEY:
      return getKey();

    case OLD_VERSION:
      return Long.valueOf(getOldVersion());

    case NEW_VALUE:
      return getNewValue();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TRANSACTION_ID:
      return isSetTransactionId();
    case BALLOT:
      return isSetBallot();
    case KEY:
      return isSetKey();
    case OLD_VERSION:
      return isSetOldVersion();
    case NEW_VALUE:
      return isSetNewValue();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Accept)
      return this.equals((Accept)that);
    return false;
  }

  public boolean equals(Accept that) {
    if (that == null)
      return false;

    boolean this_present_transactionId = true && this.isSetTransactionId();
    boolean that_present_transactionId = true && that.isSetTransactionId();
    if (this_present_transactionId || that_present_transactionId) {
      if (!(this_present_transactionId && that_present_transactionId))
        return false;
      if (!this.transactionId.equals(that.transactionId))
        return false;
    }

    boolean this_present_ballot = true && this.isSetBallot();
    boolean that_present_ballot = true && that.isSetBallot();
    if (this_present_ballot || that_present_ballot) {
      if (!(this_present_ballot && that_present_ballot))
        return false;
      if (!this.ballot.equals(that.ballot))
        return false;
    }

    boolean this_present_key = true && this.isSetKey();
    boolean that_present_key = true && that.isSetKey();
    if (this_present_key || that_present_key) {
      if (!(this_present_key && that_present_key))
        return false;
      if (!this.key.equals(that.key))
        return false;
    }

    boolean this_present_oldVersion = true;
    boolean that_present_oldVersion = true;
    if (this_present_oldVersion || that_present_oldVersion) {
      if (!(this_present_oldVersion && that_present_oldVersion))
        return false;
      if (this.oldVersion != that.oldVersion)
        return false;
    }

    boolean this_present_newValue = true && this.isSetNewValue();
    boolean that_present_newValue = true && that.isSetNewValue();
    if (this_present_newValue || that_present_newValue) {
      if (!(this_present_newValue && that_present_newValue))
        return false;
      if (!this.newValue.equals(that.newValue))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Accept other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Accept typedOther = (Accept)other;

    lastComparison = Boolean.valueOf(isSetTransactionId()).compareTo(typedOther.isSetTransactionId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTransactionId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.transactionId, typedOther.transactionId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBallot()).compareTo(typedOther.isSetBallot());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBallot()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ballot, typedOther.ballot);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetKey()).compareTo(typedOther.isSetKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.key, typedOther.key);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOldVersion()).compareTo(typedOther.isSetOldVersion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOldVersion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.oldVersion, typedOther.oldVersion);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNewValue()).compareTo(typedOther.isSetNewValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNewValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.newValue, typedOther.newValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Accept(");
    boolean first = true;

    sb.append("transactionId:");
    if (this.transactionId == null) {
      sb.append("null");
    } else {
      sb.append(this.transactionId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ballot:");
    if (this.ballot == null) {
      sb.append("null");
    } else {
      sb.append(this.ballot);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("key:");
    if (this.key == null) {
      sb.append("null");
    } else {
      sb.append(this.key);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("oldVersion:");
    sb.append(this.oldVersion);
    first = false;
    if (!first) sb.append(", ");
    sb.append("newValue:");
    if (this.newValue == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.newValue, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (ballot != null) {
      ballot.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AcceptStandardSchemeFactory implements SchemeFactory {
    public AcceptStandardScheme getScheme() {
      return new AcceptStandardScheme();
    }
  }

  private static class AcceptStandardScheme extends StandardScheme<Accept> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Accept struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TRANSACTION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.transactionId = iprot.readString();
              struct.setTransactionIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BALLOT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.ballot = new BallotNumber();
              struct.ballot.read(iprot);
              struct.setBallotIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.key = iprot.readString();
              struct.setKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // OLD_VERSION
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.oldVersion = iprot.readI64();
              struct.setOldVersionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // NEW_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.newValue = iprot.readBinary();
              struct.setNewValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Accept struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.transactionId != null) {
        oprot.writeFieldBegin(TRANSACTION_ID_FIELD_DESC);
        oprot.writeString(struct.transactionId);
        oprot.writeFieldEnd();
      }
      if (struct.ballot != null) {
        oprot.writeFieldBegin(BALLOT_FIELD_DESC);
        struct.ballot.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.key != null) {
        oprot.writeFieldBegin(KEY_FIELD_DESC);
        oprot.writeString(struct.key);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(OLD_VERSION_FIELD_DESC);
      oprot.writeI64(struct.oldVersion);
      oprot.writeFieldEnd();
      if (struct.newValue != null) {
        oprot.writeFieldBegin(NEW_VALUE_FIELD_DESC);
        oprot.writeBinary(struct.newValue);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AcceptTupleSchemeFactory implements SchemeFactory {
    public AcceptTupleScheme getScheme() {
      return new AcceptTupleScheme();
    }
  }

  private static class AcceptTupleScheme extends TupleScheme<Accept> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Accept struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTransactionId()) {
        optionals.set(0);
      }
      if (struct.isSetBallot()) {
        optionals.set(1);
      }
      if (struct.isSetKey()) {
        optionals.set(2);
      }
      if (struct.isSetOldVersion()) {
        optionals.set(3);
      }
      if (struct.isSetNewValue()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetTransactionId()) {
        oprot.writeString(struct.transactionId);
      }
      if (struct.isSetBallot()) {
        struct.ballot.write(oprot);
      }
      if (struct.isSetKey()) {
        oprot.writeString(struct.key);
      }
      if (struct.isSetOldVersion()) {
        oprot.writeI64(struct.oldVersion);
      }
      if (struct.isSetNewValue()) {
        oprot.writeBinary(struct.newValue);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Accept struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.transactionId = iprot.readString();
        struct.setTransactionIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.ballot = new BallotNumber();
        struct.ballot.read(iprot);
        struct.setBallotIsSet(true);
      }
      if (incoming.get(2)) {
        struct.key = iprot.readString();
        struct.setKeyIsSet(true);
      }
      if (incoming.get(3)) {
        struct.oldVersion = iprot.readI64();
        struct.setOldVersionIsSet(true);
      }
      if (incoming.get(4)) {
        struct.newValue = iprot.readBinary();
        struct.setNewValueIsSet(true);
      }
    }
  }

}

