/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.ucsb.cs.mdcc.messaging;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class RecordVersion implements org.apache.thrift.TBase<RecordVersion, RecordVersion._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RecordVersion");

  private static final org.apache.thrift.protocol.TField BALLOT_FIELD_DESC = new org.apache.thrift.protocol.TField("ballot", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField PROCESS_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("processId", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RecordVersionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RecordVersionTupleSchemeFactory());
  }

  public long ballot; // required
  public String processId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BALLOT((short)1, "ballot"),
    PROCESS_ID((short)2, "processId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BALLOT
          return BALLOT;
        case 2: // PROCESS_ID
          return PROCESS_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __BALLOT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BALLOT, new org.apache.thrift.meta_data.FieldMetaData("ballot", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.PROCESS_ID, new org.apache.thrift.meta_data.FieldMetaData("processId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RecordVersion.class, metaDataMap);
  }

  public RecordVersion() {
  }

  public RecordVersion(
    long ballot,
    String processId)
  {
    this();
    this.ballot = ballot;
    setBallotIsSet(true);
    this.processId = processId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RecordVersion(RecordVersion other) {
    __isset_bitfield = other.__isset_bitfield;
    this.ballot = other.ballot;
    if (other.isSetProcessId()) {
      this.processId = other.processId;
    }
  }

  public RecordVersion deepCopy() {
    return new RecordVersion(this);
  }

  @Override
  public void clear() {
    setBallotIsSet(false);
    this.ballot = 0;
    this.processId = null;
  }

  public long getBallot() {
    return this.ballot;
  }

  public RecordVersion setBallot(long ballot) {
    this.ballot = ballot;
    setBallotIsSet(true);
    return this;
  }

  public void unsetBallot() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __BALLOT_ISSET_ID);
  }

  /** Returns true if field ballot is set (has been assigned a value) and false otherwise */
  public boolean isSetBallot() {
    return EncodingUtils.testBit(__isset_bitfield, __BALLOT_ISSET_ID);
  }

  public void setBallotIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __BALLOT_ISSET_ID, value);
  }

  public String getProcessId() {
    return this.processId;
  }

  public RecordVersion setProcessId(String processId) {
    this.processId = processId;
    return this;
  }

  public void unsetProcessId() {
    this.processId = null;
  }

  /** Returns true if field processId is set (has been assigned a value) and false otherwise */
  public boolean isSetProcessId() {
    return this.processId != null;
  }

  public void setProcessIdIsSet(boolean value) {
    if (!value) {
      this.processId = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case BALLOT:
      if (value == null) {
        unsetBallot();
      } else {
        setBallot((Long)value);
      }
      break;

    case PROCESS_ID:
      if (value == null) {
        unsetProcessId();
      } else {
        setProcessId((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BALLOT:
      return Long.valueOf(getBallot());

    case PROCESS_ID:
      return getProcessId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BALLOT:
      return isSetBallot();
    case PROCESS_ID:
      return isSetProcessId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RecordVersion)
      return this.equals((RecordVersion)that);
    return false;
  }

  public boolean equals(RecordVersion that) {
    if (that == null)
      return false;

    boolean this_present_ballot = true;
    boolean that_present_ballot = true;
    if (this_present_ballot || that_present_ballot) {
      if (!(this_present_ballot && that_present_ballot))
        return false;
      if (this.ballot != that.ballot)
        return false;
    }

    boolean this_present_processId = true && this.isSetProcessId();
    boolean that_present_processId = true && that.isSetProcessId();
    if (this_present_processId || that_present_processId) {
      if (!(this_present_processId && that_present_processId))
        return false;
      if (!this.processId.equals(that.processId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(RecordVersion other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    RecordVersion typedOther = (RecordVersion)other;

    lastComparison = Boolean.valueOf(isSetBallot()).compareTo(typedOther.isSetBallot());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBallot()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ballot, typedOther.ballot);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProcessId()).compareTo(typedOther.isSetProcessId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProcessId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.processId, typedOther.processId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RecordVersion(");
    boolean first = true;

    sb.append("ballot:");
    sb.append(this.ballot);
    first = false;
    if (!first) sb.append(", ");
    sb.append("processId:");
    if (this.processId == null) {
      sb.append("null");
    } else {
      sb.append(this.processId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RecordVersionStandardSchemeFactory implements SchemeFactory {
    public RecordVersionStandardScheme getScheme() {
      return new RecordVersionStandardScheme();
    }
  }

  private static class RecordVersionStandardScheme extends StandardScheme<RecordVersion> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RecordVersion struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BALLOT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.ballot = iprot.readI64();
              struct.setBallotIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PROCESS_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.processId = iprot.readString();
              struct.setProcessIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RecordVersion struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(BALLOT_FIELD_DESC);
      oprot.writeI64(struct.ballot);
      oprot.writeFieldEnd();
      if (struct.processId != null) {
        oprot.writeFieldBegin(PROCESS_ID_FIELD_DESC);
        oprot.writeString(struct.processId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RecordVersionTupleSchemeFactory implements SchemeFactory {
    public RecordVersionTupleScheme getScheme() {
      return new RecordVersionTupleScheme();
    }
  }

  private static class RecordVersionTupleScheme extends TupleScheme<RecordVersion> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RecordVersion struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetBallot()) {
        optionals.set(0);
      }
      if (struct.isSetProcessId()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetBallot()) {
        oprot.writeI64(struct.ballot);
      }
      if (struct.isSetProcessId()) {
        oprot.writeString(struct.processId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RecordVersion struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.ballot = iprot.readI64();
        struct.setBallotIsSet(true);
      }
      if (incoming.get(1)) {
        struct.processId = iprot.readString();
        struct.setProcessIdIsSet(true);
      }
    }
  }

}

